service: serverlessproject

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

plugins:
  - serverless-offline

functions:
  getUser:
    handler: lambds/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true
